# Experiment 2 - Relations

Now that we have our model capable of detecting components, let us move on to estimating the number of relations. Initially, we considered splitting each abstract into sentences and labeling all possible combinations of sentences as either `No related` or `Related`, corresponding to 0 and 1, respectively. However, this led to an imbalanced and overly difficult task, as the majority of sentence pairs were unrelated. 

To address this, we approached the problem differently. Instead of trying to predict relationships between all possible sentence pairs, we reformulated the task to focus on the components directly. Specifically, we label each component as either *In a relationship* or *Not in a relationship*. A component is considered *In a relationship* if it serves as the first member (*source*) of at least one relation, and *Not in a relationship* otherwise. 
Consider the following annotation:

    R1	Partial-Attack Arg1:T10 Arg2:T11	
    R2	Support Arg1:T8 Arg2:T9	
    R3	Support Arg1:T7 Arg2:T10	
    R4	Support Arg1:T6 Arg2:T10	
    R5	Support Arg1:T5 Arg2:T9	
    R6	Support Arg1:T2 Arg2:T4	
    R7	Partial-Attack Arg1:T3 Arg2:T4	
    R8	Partial-Attack Arg1:T1 Arg2:T4	

In this annotation, there are eight relations, corresponding to the `R1` through `R8` entries. Each relation has a source, marked as `Arg1`, and a target, marked as `Arg2`. For example, in `R1`, `T10` is the source, and `T11` is the target. Using this information, we label components based on whether they appear as `Arg1` in any relation. Components like `T1`, `T2`, `T3`, `T5`, `T6`, `T7`, `T8`, and `T10` are labeled as `Relationship` (1), while components like `T4`, `T9`, and `T11` are labeled as `Not relationship` (0), as well as non-components. This reformulation simplifies the task from predicting relationships between pairs of sentences to predicting whether a given component participates in an outgoing relationship.

In [ ]:
from experiment_2_code import *

C:\Users\Antonio\anaconda3\envs\NLP\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Antonio\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Antonio\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


### 1. Preprocessing
Here we preprocess our data by splitting the abstracts into sentences. Each combination of two sentences is then labeled as either being a `Relationship`, labeled as `1`, or `Not relationship`, labeled as `0`.

In [10]:
train_set = read_brat_dataset('../data/train/neoplasm_train') 
val_set = read_brat_dataset('../data/dev/neoplasm_dev')

glaucoma_test = read_brat_dataset('../data/test/glaucoma_test')
neoplasm_test = read_brat_dataset('../data/test/neoplasm_test')
mixed_test = read_brat_dataset('../data/test/mixed_test')

test_set = glaucoma_test + neoplasm_test + mixed_test

It happens 24 times that a component is already in a relation in neoplasm_train.
It happens 4 times that a component is already in a relation in neoplasm_dev.
It happens 21 times that a component is already in a relation in glaucoma_test.
It happens 5 times that a component is already in a relation in neoplasm_test.
It happens 9 times that a component is already in a relation in mixed_test.


In [11]:
label_counts_train, avg_sentences_per_file_train = compute_dataset_statistics(train_set, dataset_name="train")
label_counts_test, avg_sentences_per_file_test = compute_dataset_statistics(test_set, dataset_name="test")

- Train set:
	Label 0: 3251 samples
	Label 1: 1394 samples

	There are 2 different labels in the train set -> [0, 1]
	Average number of sentences per file in train set: 13
	Max sentence length: 107
	Average relationships per file: 4.06
	Average no relationships per file: 9.29

- Test set:
	Label 0: 2743 samples
	Label 1: 1085 samples

	There are 2 different labels in the test set -> [0, 1]
	Average number of sentences per file in test set: 14
	Max sentence length: 91
	Average relationships per file: 4.09
	Average no relationships per file: 10.20



In [12]:
train_collection = FilenameLabelledCollection([data['sentence'] for data in train_set], 
                                                 [data['label'] for data in train_set], 
                                                 [data['filename'] for data in train_set])

# train_collection, val_collection = train_collection.split_stratified(0.7)
# train_collection, val_collection = train_collection.split_stratified_by_filenames(0.75)
val_collection = FilenameLabelledCollection([data['sentence'] for data in val_set], 
                                                 [data['label'] for data in val_set], 
                                                 [data['filename'] for data in val_set])

test_collection = FilenameLabelledCollection([data['sentence'] for data in test_set], 
                                                 [data['label'] for data in test_set], 
                                                 [data['filename'] for data in test_set])

glaucoma_collection = FilenameLabelledCollection([data['sentence'] for data in glaucoma_test], 
                                                 [data['label'] for data in glaucoma_test], 
                                                 [data['filename'] for data in glaucoma_test])

neoplasm_collection = FilenameLabelledCollection([data['sentence'] for data in neoplasm_test], 
                                                 [data['label'] for data in neoplasm_test], 
                                                 [data['filename'] for data in neoplasm_test])

mixed_collection = FilenameLabelledCollection([data['sentence'] for data in mixed_test], 
                                                 [data['label'] for data in mixed_test], 
                                                 [data['filename'] for data in mixed_test])

In [13]:
indexer = qp.data.preprocessing.IndexTransformer(min_df=1)

# Create and index the dataset
abs_dataset = CustomDataset(training=train_collection, test=test_collection, val=val_collection)
index(abs_dataset, indexer, inplace=True)

# Index the test collections
index(glaucoma_collection, indexer, fit=False, inplace=True)
index(neoplasm_collection, indexer, fit=False, inplace=True)
index(mixed_collection, indexer, fit=False, inplace=True)

qp.environ['SAMPLE_SIZE'] = avg_sentences_per_file_train

indexing: 100%|███████████████████████████████████████████████| 1208/1208 [00:00<00:00, 75498.72it/s]


### 2. Classifier

In [7]:
study = optuna.create_study(direction="maximize")
study.optimize(lambda trial: objective(trial, abs_dataset), n_trials=50)

print("Best trial:")
trial = study.best_trial
print(f"  Macro F1 Score: {trial.value}")
print("  Params:")
for key, value in trial.params.items():
    print(f"    {key}: {value}")

[I 2024-10-30 16:26:42,953] A new study created in memory with name: no-name-e3381943-a2e9-44f2-bd9f-bc1bdcb97ef5


Starting trial 0 with parameters:
    Embedding size: 172 - Hidden size: 281
    Optimizer: Adam (lr: 0.0008485856927597929) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 12, 'T_mult': 5})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=7 tr-loss=0.14423 tr-acc=94.66% tr-macroF1=93.62% patience=1/5 val-loss=0.530C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 2
Performing a final training pass over the validation set...


[I 2024-10-30 16:29:40,136] Trial 0 finished with value: 0.8037904523511532 and parameters: {'embedding_size': 172, 'hidden_size': 281, 'optimizer': 'Adam', 'lr': 0.0008485856927597929, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 12, 'T_mult': 5}. Best is trial 0 with value: 0.8037904523511532.


[Training complete] - Best loss on validation set: 0.40404292941093445 - Best f1 on validation set: 0.8037904523511532
Starting trial 1 with parameters:
    Embedding size: 196 - Hidden size: 273
    Optimizer: Adam (lr: 0.00038589816919175904) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 4, 'T_mult': 2})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=23 tr-loss=0.01614 tr-acc=99.44% tr-macroF1=99.33% patience=1/5 val-loss=0.64C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 18
Performing a final training pass over the validation set...


[I 2024-10-30 16:40:17,044] Trial 1 finished with value: 0.8003767700081093 and parameters: {'embedding_size': 196, 'hidden_size': 273, 'optimizer': 'Adam', 'lr': 0.00038589816919175904, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 4, 'T_mult': 2}. Best is trial 0 with value: 0.8037904523511532.


[Training complete] - Best loss on validation set: 0.5891496539115906 - Best f1 on validation set: 0.8003767700081093
Starting trial 2 with parameters:
    Embedding size: 123 - Hidden size: 275
    Optimizer: Adam (lr: 2.3829920272740206e-05) - Scheduler: CosineAnnealingLR (params: {'T_max': 7})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=45 tr-loss=0.30593 tr-acc=87.06% tr-macroF1=83.83% patience=1/5 val-loss=0.44C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 40
Performing a final training pass over the validation set...


[I 2024-10-30 16:53:46,262] Trial 2 finished with value: 0.7188190729739279 and parameters: {'embedding_size': 123, 'hidden_size': 275, 'optimizer': 'Adam', 'lr': 2.3829920272740206e-05, 'scheduler': 'CosineAnnealingLR', 'T_max': 7}. Best is trial 0 with value: 0.8037904523511532.


[Training complete] - Best loss on validation set: 0.4410031884908676 - Best f1 on validation set: 0.7188190729739279
Starting trial 3 with parameters:
    Embedding size: 128 - Hidden size: 291
    Optimizer: Adam (lr: 9.94339477109365e-05) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 4, 'T_mult': 5})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=8 tr-loss=0.35579 tr-acc=84.67% tr-macroF1=80.56% patience=1/5 val-loss=0.462C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 3
Performing a final training pass over the validation set...


[I 2024-10-30 16:56:26,466] Trial 3 finished with value: 0.69437834128416 and parameters: {'embedding_size': 128, 'hidden_size': 291, 'optimizer': 'Adam', 'lr': 9.94339477109365e-05, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 4, 'T_mult': 5}. Best is trial 0 with value: 0.8037904523511532.


[Training complete] - Best loss on validation set: 0.5168560743331909 - Best f1 on validation set: 0.69437834128416
Starting trial 4 with parameters:
    Embedding size: 199 - Hidden size: 271
    Optimizer: Adam (lr: 0.0003889299826688172) - Scheduler: CosineAnnealingLR (params: {'T_max': 5})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=10 tr-loss=0.04451 tr-acc=99.03% tr-macroF1=98.85% patience=1/5 val-loss=0.52C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 5
Performing a final training pass over the validation set...


[I 2024-10-30 17:00:55,030] Trial 4 finished with value: 0.7772035053925448 and parameters: {'embedding_size': 199, 'hidden_size': 271, 'optimizer': 'Adam', 'lr': 0.0003889299826688172, 'scheduler': 'CosineAnnealingLR', 'T_max': 5}. Best is trial 0 with value: 0.8037904523511532.


[Training complete] - Best loss on validation set: 0.41115377843379974 - Best f1 on validation set: 0.7772035053925448
Starting trial 5 with parameters:
    Embedding size: 125 - Hidden size: 275
    Optimizer: Adam (lr: 0.00010211906915266462) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 7, 'T_mult': 5})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=13 tr-loss=0.21717 tr-acc=91.80% tr-macroF1=90.01% patience=1/5 val-loss=0.42C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 8
Performing a final training pass over the validation set...


[I 2024-10-30 17:04:55,786] Trial 5 finished with value: 0.7438892046922639 and parameters: {'embedding_size': 125, 'hidden_size': 275, 'optimizer': 'Adam', 'lr': 0.00010211906915266462, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 7, 'T_mult': 5}. Best is trial 0 with value: 0.8037904523511532.


[Training complete] - Best loss on validation set: 0.4235655516386032 - Best f1 on validation set: 0.7438892046922639
Starting trial 6 with parameters:
    Embedding size: 180 - Hidden size: 260
    Optimizer: Adam (lr: 3.328535004503496e-05) - Scheduler: CosineAnnealingLR (params: {'T_max': 3})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=35 tr-loss=0.20415 tr-acc=92.70% tr-macroF1=91.16% patience=1/5 val-loss=0.42C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 30
Performing a final training pass over the validation set...


[I 2024-10-30 17:19:00,749] Trial 6 finished with value: 0.7476459510357816 and parameters: {'embedding_size': 180, 'hidden_size': 260, 'optimizer': 'Adam', 'lr': 3.328535004503496e-05, 'scheduler': 'CosineAnnealingLR', 'T_max': 3}. Best is trial 0 with value: 0.8037904523511532.


[Training complete] - Best loss on validation set: 0.4059285819530487 - Best f1 on validation set: 0.7476459510357816
Starting trial 7 with parameters:
    Embedding size: 106 - Hidden size: 270
    Optimizer: Adam (lr: 0.0003096340575734433) - Scheduler: CosineAnnealingLR (params: {'T_max': 9})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=11 tr-loss=0.13007 tr-acc=95.52% tr-macroF1=94.65% patience=1/5 val-loss=0.46C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 6
Performing a final training pass over the validation set...


[I 2024-10-30 17:22:03,261] Trial 7 finished with value: 0.7856899617844035 and parameters: {'embedding_size': 106, 'hidden_size': 270, 'optimizer': 'Adam', 'lr': 0.0003096340575734433, 'scheduler': 'CosineAnnealingLR', 'T_max': 9}. Best is trial 0 with value: 0.8037904523511532.


[Training complete] - Best loss on validation set: 0.41388463973999023 - Best f1 on validation set: 0.7856899617844035
Starting trial 8 with parameters:
    Embedding size: 179 - Hidden size: 298
    Optimizer: Adam (lr: 0.00013230983867777723) - Scheduler: CosineAnnealingLR (params: {'T_max': 10})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=12 tr-loss=0.15421 tr-acc=95.01% tr-macroF1=94.01% patience=1/5 val-loss=0.39C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 7
Performing a final training pass over the validation set...


[I 2024-10-30 17:27:22,920] Trial 8 finished with value: 0.776202147525677 and parameters: {'embedding_size': 179, 'hidden_size': 298, 'optimizer': 'Adam', 'lr': 0.00013230983867777723, 'scheduler': 'CosineAnnealingLR', 'T_max': 10}. Best is trial 0 with value: 0.8037904523511532.


[Training complete] - Best loss on validation set: 0.4153924733400345 - Best f1 on validation set: 0.776202147525677
Starting trial 9 with parameters:
    Embedding size: 169 - Hidden size: 278
    Optimizer: Adam (lr: 0.0008006129710263081) - Scheduler: CosineAnnealingLR (params: {'T_max': 9})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=9 tr-loss=0.05723 tr-acc=98.08% tr-macroF1=97.72% patience=1/5 val-loss=0.575C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 4
Performing a final training pass over the validation set...


[I 2024-10-30 17:31:00,942] Trial 9 finished with value: 0.8068037111151537 and parameters: {'embedding_size': 169, 'hidden_size': 278, 'optimizer': 'Adam', 'lr': 0.0008006129710263081, 'scheduler': 'CosineAnnealingLR', 'T_max': 9}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.3986272066831589 - Best f1 on validation set: 0.8068037111151537
Starting trial 10 with parameters:
    Embedding size: 151 - Hidden size: 287
    Optimizer: Adam (lr: 1.0734940879113042e-05) - Scheduler: CosineAnnealingLR (params: {'T_max': 12})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=6 tr-loss=0.60343 tr-acc=69.69% tr-macroF1=46.09% patience=1/5 val-loss=0.592C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 1
Performing a final training pass over the validation set...


[I 2024-10-30 17:33:18,468] Trial 10 finished with value: 0.4104912572855953 and parameters: {'embedding_size': 151, 'hidden_size': 287, 'optimizer': 'Adam', 'lr': 1.0734940879113042e-05, 'scheduler': 'CosineAnnealingLR', 'T_max': 12}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.6156531870365143 - Best f1 on validation set: 0.4104912572855953
Starting trial 11 with parameters:
    Embedding size: 154 - Hidden size: 284
    Optimizer: Adam (lr: 0.0009064651384380115) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 12, 'T_mult': 4})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=9 tr-loss=0.03925 tr-acc=98.60% tr-macroF1=98.33% patience=1/5 val-loss=0.683C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 4
Performing a final training pass over the validation set...


[I 2024-10-30 17:36:41,538] Trial 11 finished with value: 0.772732212951706 and parameters: {'embedding_size': 154, 'hidden_size': 284, 'optimizer': 'Adam', 'lr': 0.0009064651384380115, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 12, 'T_mult': 4}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.44012413918972015 - Best f1 on validation set: 0.772732212951706
Starting trial 12 with parameters:
    Embedding size: 167 - Hidden size: 281
    Optimizer: Adam (lr: 0.0009710587639767617) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 11, 'T_mult': 1})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=15 tr-loss=0.04787 tr-acc=98.36% tr-macroF1=98.05% patience=1/5 val-loss=0.66C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 10
Performing a final training pass over the validation set...


[I 2024-10-30 17:42:34,853] Trial 12 finished with value: 0.7848657943396893 and parameters: {'embedding_size': 167, 'hidden_size': 281, 'optimizer': 'Adam', 'lr': 0.0009710587639767617, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 11, 'T_mult': 1}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.646946519613266 - Best f1 on validation set: 0.7848657943396893
Starting trial 13 with parameters:
    Embedding size: 168 - Hidden size: 262
    Optimizer: Adam (lr: 0.0005682106988700279) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 9, 'T_mult': 3})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=11 tr-loss=0.03212 tr-acc=98.97% tr-macroF1=98.77% patience=1/5 val-loss=0.57C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 6
Performing a final training pass over the validation set...


[I 2024-10-30 17:46:46,315] Trial 13 finished with value: 0.8031364698031365 and parameters: {'embedding_size': 168, 'hidden_size': 262, 'optimizer': 'Adam', 'lr': 0.0005682106988700279, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 9, 'T_mult': 3}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.4530303329229355 - Best f1 on validation set: 0.8031364698031365
Starting trial 14 with parameters:
    Embedding size: 167 - Hidden size: 292
    Optimizer: Adam (lr: 0.00019006947169647595) - Scheduler: CosineAnnealingLR (params: {'T_max': 7})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=11 tr-loss=0.15313 tr-acc=95.05% tr-macroF1=94.07% patience=1/5 val-loss=0.44C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 6
Performing a final training pass over the validation set...


[I 2024-10-30 17:51:19,517] Trial 14 finished with value: 0.7697040885475491 and parameters: {'embedding_size': 167, 'hidden_size': 292, 'optimizer': 'Adam', 'lr': 0.00019006947169647595, 'scheduler': 'CosineAnnealingLR', 'T_max': 7}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.4690325856208801 - Best f1 on validation set: 0.7697040885475491
Starting trial 15 with parameters:
    Embedding size: 142 - Hidden size: 266
    Optimizer: Adam (lr: 0.0006219422225430925) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 1, 'T_mult': 4})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=8 tr-loss=0.11021 tr-acc=95.93% tr-macroF1=95.15% patience=1/5 val-loss=0.477C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 3
Performing a final training pass over the validation set...



[I 2024-10-30 17:54:05,435] Trial 15 finished with value: 0.7923653846153846 and parameters: {'embedding_size': 142, 'hidden_size': 266, 'optimizer': 'Adam', 'lr': 0.0006219422225430925, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 1, 'T_mult': 4}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.3758814185857773 - Best f1 on validation set: 0.7923653846153846
Starting trial 16 with parameters:
    Embedding size: 184 - Hidden size: 279
    Optimizer: Adam (lr: 0.0002159521825089592) - Scheduler: CosineAnnealingLR (params: {'T_max': 12})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=16 tr-loss=0.03758 tr-acc=98.92% tr-macroF1=98.72% patience=1/5 val-loss=0.53C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 11
Performing a final training pass over the validation set...


[I 2024-10-30 18:00:50,125] Trial 16 finished with value: 0.7833620195065978 and parameters: {'embedding_size': 184, 'hidden_size': 279, 'optimizer': 'Adam', 'lr': 0.0002159521825089592, 'scheduler': 'CosineAnnealingLR', 'T_max': 12}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.4374668449163437 - Best f1 on validation set: 0.7833620195065978
Starting trial 17 with parameters:
    Embedding size: 159 - Hidden size: 286
    Optimizer: Adam (lr: 6.371478135497518e-05) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 9, 'T_mult': 3})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=23 tr-loss=0.12668 tr-acc=95.54% tr-macroF1=94.67% patience=1/5 val-loss=0.45C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 18
Performing a final training pass over the validation set...


[I 2024-10-30 18:09:52,817] Trial 17 finished with value: 0.7682145082425996 and parameters: {'embedding_size': 159, 'hidden_size': 286, 'optimizer': 'Adam', 'lr': 6.371478135497518e-05, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 9, 'T_mult': 3}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.41532444953918457 - Best f1 on validation set: 0.7682145082425996
Starting trial 18 with parameters:
    Embedding size: 136 - Hidden size: 299
    Optimizer: Adam (lr: 0.0005983679698782991) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 10, 'T_mult': 5})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=7 tr-loss=0.11781 tr-acc=95.29% tr-macroF1=94.37% patience=1/5 val-loss=0.448C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 2
Performing a final training pass over the validation set...


[I 2024-10-30 18:12:11,816] Trial 18 finished with value: 0.782733224222586 and parameters: {'embedding_size': 136, 'hidden_size': 299, 'optimizer': 'Adam', 'lr': 0.0005983679698782991, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 10, 'T_mult': 5}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.3951180726289749 - Best f1 on validation set: 0.782733224222586
Starting trial 19 with parameters:
    Embedding size: 186 - Hidden size: 266
    Optimizer: Adam (lr: 0.00024826339125217343) - Scheduler: CosineAnnealingLR (params: {'T_max': 2})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=10 tr-loss=0.08095 tr-acc=97.40% tr-macroF1=96.88% patience=1/5 val-loss=0.46C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 5
Performing a final training pass over the validation set...


[I 2024-10-30 18:16:11,319] Trial 19 finished with value: 0.7598104246204949 and parameters: {'embedding_size': 186, 'hidden_size': 266, 'optimizer': 'Adam', 'lr': 0.00024826339125217343, 'scheduler': 'CosineAnnealingLR', 'T_max': 2}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.41375014185905457 - Best f1 on validation set: 0.7598104246204949
Starting trial 20 with parameters:
    Embedding size: 173 - Hidden size: 281
    Optimizer: Adam (lr: 5.720121019225376e-05) - Scheduler: CosineAnnealingLR (params: {'T_max': 8})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=28 tr-loss=0.13907 tr-acc=95.39% tr-macroF1=94.47% patience=1/5 val-loss=0.43C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 23
Performing a final training pass over the validation set...


[I 2024-10-30 18:26:48,344] Trial 20 finished with value: 0.7593622543566927 and parameters: {'embedding_size': 173, 'hidden_size': 281, 'optimizer': 'Adam', 'lr': 5.720121019225376e-05, 'scheduler': 'CosineAnnealingLR', 'T_max': 8}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.4100693017244339 - Best f1 on validation set: 0.7593622543566927
Starting trial 21 with parameters:
    Embedding size: 162 - Hidden size: 257
    Optimizer: Adam (lr: 0.000596095526672219) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 8, 'T_mult': 3})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=12 tr-loss=0.02565 tr-acc=99.29% tr-macroF1=99.15% patience=1/5 val-loss=0.64C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 7
Performing a final training pass over the validation set...


[I 2024-10-30 18:30:50,296] Trial 21 finished with value: 0.7669802626915248 and parameters: {'embedding_size': 162, 'hidden_size': 257, 'optimizer': 'Adam', 'lr': 0.000596095526672219, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 8, 'T_mult': 3}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.4672970771789551 - Best f1 on validation set: 0.7669802626915248
Starting trial 22 with parameters:
    Embedding size: 172 - Hidden size: 263
    Optimizer: Adam (lr: 0.0005589533046794249) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 12, 'T_mult': 2})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=9 tr-loss=0.05242 tr-acc=98.11% tr-macroF1=97.74% patience=1/5 val-loss=0.473C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 4
Performing a final training pass over the validation set...


[I 2024-10-30 18:34:01,483] Trial 22 finished with value: 0.7939602874348011 and parameters: {'embedding_size': 172, 'hidden_size': 263, 'optimizer': 'Adam', 'lr': 0.0005589533046794249, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 12, 'T_mult': 2}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.3784707486629486 - Best f1 on validation set: 0.7939602874348011
Starting trial 23 with parameters:
    Embedding size: 145 - Hidden size: 256
    Optimizer: Adam (lr: 0.0009968532374448032) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 10, 'T_mult': 4})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=11 tr-loss=0.01987 tr-acc=99.48% tr-macroF1=99.38% patience=1/5 val-loss=0.66C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 6
Performing a final training pass over the validation set...


[I 2024-10-30 18:37:23,277] Trial 23 finished with value: 0.7481177347989132 and parameters: {'embedding_size': 145, 'hidden_size': 256, 'optimizer': 'Adam', 'lr': 0.0009968532374448032, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 10, 'T_mult': 4}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.5684578120708466 - Best f1 on validation set: 0.7481177347989132
Starting trial 24 with parameters:
    Embedding size: 190 - Hidden size: 291
    Optimizer: Adam (lr: 0.000426838445544328) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 6, 'T_mult': 2})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=18 tr-loss=0.01842 tr-acc=99.42% tr-macroF1=99.31% patience=1/5 val-loss=0.63C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 13
Performing a final training pass over the validation set...


[I 2024-10-30 18:45:04,660] Trial 24 finished with value: 0.7971409154090783 and parameters: {'embedding_size': 190, 'hidden_size': 291, 'optimizer': 'Adam', 'lr': 0.000426838445544328, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 6, 'T_mult': 2}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.5206275582313538 - Best f1 on validation set: 0.7971409154090783
Starting trial 25 with parameters:
    Embedding size: 173 - Hidden size: 268
    Optimizer: Adam (lr: 0.0006626704845400004) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 9, 'T_mult': 3})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=12 tr-loss=0.01855 tr-acc=99.53% tr-macroF1=99.44% patience=1/5 val-loss=0.61C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 7
Performing a final training pass over the validation set...


[I 2024-10-30 18:49:22,336] Trial 25 finished with value: 0.7997334381682024 and parameters: {'embedding_size': 173, 'hidden_size': 268, 'optimizer': 'Adam', 'lr': 0.0006626704845400004, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 9, 'T_mult': 3}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.4875870794057846 - Best f1 on validation set: 0.7997334381682024
Starting trial 26 with parameters:
    Embedding size: 156 - Hidden size: 277
    Optimizer: Adam (lr: 0.0003167393235445352) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 12, 'T_mult': 4})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=27 tr-loss=0.02078 tr-acc=99.20% tr-macroF1=99.05% patience=1/5 val-loss=0.80C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 22
Performing a final training pass over the validation set...


[I 2024-10-30 18:58:09,188] Trial 26 finished with value: 0.7888822350862407 and parameters: {'embedding_size': 156, 'hidden_size': 277, 'optimizer': 'Adam', 'lr': 0.0003167393235445352, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 12, 'T_mult': 4}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.6176514625549316 - Best f1 on validation set: 0.7888822350862407
Starting trial 27 with parameters:
    Embedding size: 163 - Hidden size: 262
    Optimizer: Adam (lr: 0.0007883398409050293) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 6, 'T_mult': 1})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=13 tr-loss=0.02720 tr-acc=99.42% tr-macroF1=99.31% patience=1/5 val-loss=0.73C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 8
Performing a final training pass over the validation set...


[I 2024-10-30 19:02:30,779] Trial 27 finished with value: 0.7903071348885884 and parameters: {'embedding_size': 163, 'hidden_size': 262, 'optimizer': 'Adam', 'lr': 0.0007883398409050293, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 6, 'T_mult': 1}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.5102259069681168 - Best f1 on validation set: 0.7903071348885884
Starting trial 28 with parameters:
    Embedding size: 192 - Hidden size: 294
    Optimizer: Adam (lr: 0.0004774788218341842) - Scheduler: CosineAnnealingLR (params: {'T_max': 5})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=10 tr-loss=0.10045 tr-acc=96.28% tr-macroF1=95.57% patience=1/5 val-loss=0.46C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 5
Performing a final training pass over the validation set...


[I 2024-10-30 19:06:41,774] Trial 28 finished with value: 0.7899743230625583 and parameters: {'embedding_size': 192, 'hidden_size': 294, 'optimizer': 'Adam', 'lr': 0.0004774788218341842, 'scheduler': 'CosineAnnealingLR', 'T_max': 5}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.38049736618995667 - Best f1 on validation set: 0.7899743230625583
Starting trial 29 with parameters:
    Embedding size: 177 - Hidden size: 273
    Optimizer: Adam (lr: 0.0001553057482756347) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 10, 'T_mult': 3})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=11 tr-loss=0.09503 tr-acc=97.27% tr-macroF1=96.74% patience=1/5 val-loss=0.48C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 6
Performing a final training pass over the validation set...


[I 2024-10-30 19:10:47,047] Trial 29 finished with value: 0.7870817872475451 and parameters: {'embedding_size': 177, 'hidden_size': 273, 'optimizer': 'Adam', 'lr': 0.0001553057482756347, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 10, 'T_mult': 3}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.429781973361969 - Best f1 on validation set: 0.7870817872475451
Starting trial 30 with parameters:
    Embedding size: 147 - Hidden size: 285
    Optimizer: Adam (lr: 0.00032062025401670543) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 8, 'T_mult': 2})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=14 tr-loss=0.03786 tr-acc=98.90% tr-macroF1=98.69% patience=1/5 val-loss=0.49C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 9
Performing a final training pass over the validation set...


[I 2024-10-30 19:15:17,092] Trial 30 finished with value: 0.7812346277157187 and parameters: {'embedding_size': 147, 'hidden_size': 285, 'optimizer': 'Adam', 'lr': 0.00032062025401670543, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 8, 'T_mult': 2}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.4391588568687439 - Best f1 on validation set: 0.7812346277157187
Starting trial 31 with parameters:
    Embedding size: 199 - Hidden size: 276
    Optimizer: Adam (lr: 0.00040765525110272237) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 4, 'T_mult': 2})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=10 tr-loss=0.05688 tr-acc=98.06% tr-macroF1=97.69% patience=1/5 val-loss=0.51C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 5
Performing a final training pass over the validation set...


[I 2024-10-30 19:19:25,631] Trial 31 finished with value: 0.7937773070303191 and parameters: {'embedding_size': 199, 'hidden_size': 276, 'optimizer': 'Adam', 'lr': 0.00040765525110272237, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 4, 'T_mult': 2}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.39496470987796783 - Best f1 on validation set: 0.7937773070303191
Starting trial 32 with parameters:
    Embedding size: 192 - Hidden size: 273
    Optimizer: Adam (lr: 0.0008105724333512531) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 4, 'T_mult': 2})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=7 tr-loss=0.05091 tr-acc=98.34% tr-macroF1=98.02% patience=1/5 val-loss=0.485C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 2
Performing a final training pass over the validation set...


[I 2024-10-30 19:22:14,628] Trial 32 finished with value: 0.7791919321777263 and parameters: {'embedding_size': 192, 'hidden_size': 273, 'optimizer': 'Adam', 'lr': 0.0008105724333512531, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 4, 'T_mult': 2}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.4050210416316986 - Best f1 on validation set: 0.7791919321777263
Starting trial 33 with parameters:
    Embedding size: 166 - Hidden size: 281
    Optimizer: Adam (lr: 0.00046563338303563654) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 2, 'T_mult': 3})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=13 tr-loss=0.07408 tr-acc=97.63% tr-macroF1=97.18% patience=1/5 val-loss=0.72C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 8
Performing a final training pass over the validation set...


[I 2024-10-30 19:26:52,916] Trial 33 finished with value: 0.7899743230625583 and parameters: {'embedding_size': 166, 'hidden_size': 281, 'optimizer': 'Adam', 'lr': 0.00046563338303563654, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 2, 'T_mult': 3}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.4403691589832306 - Best f1 on validation set: 0.7899743230625583
Starting trial 34 with parameters:
    Embedding size: 135 - Hidden size: 273
    Optimizer: Adam (lr: 0.0007545644559317492) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 5, 'T_mult': 1})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=10 tr-loss=0.04028 tr-acc=98.64% tr-macroF1=98.39% patience=1/5 val-loss=0.72C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 5
Performing a final training pass over the validation set...


[I 2024-10-30 19:29:53,826] Trial 34 finished with value: 0.7725163801058506 and parameters: {'embedding_size': 135, 'hidden_size': 273, 'optimizer': 'Adam', 'lr': 0.0007545644559317492, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 5, 'T_mult': 1}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.42851191759109497 - Best f1 on validation set: 0.7725163801058506
Starting trial 35 with parameters:
    Embedding size: 116 - Hidden size: 279
    Optimizer: Adam (lr: 0.00028844696620494324) - Scheduler: CosineAnnealingLR (params: {'T_max': 10})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=18 tr-loss=0.05690 tr-acc=98.04% tr-macroF1=97.66% patience=1/5 val-loss=0.52C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 13
Performing a final training pass over the validation set...


[I 2024-10-30 19:34:40,137] Trial 35 finished with value: 0.7829169260501547 and parameters: {'embedding_size': 116, 'hidden_size': 279, 'optimizer': 'Adam', 'lr': 0.00028844696620494324, 'scheduler': 'CosineAnnealingLR', 'T_max': 10}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.42854996025562286 - Best f1 on validation set: 0.7829169260501547
Starting trial 36 with parameters:
    Embedding size: 185 - Hidden size: 268
    Optimizer: Adam (lr: 0.0003668286526745206) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 3, 'T_mult': 3})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=13 tr-loss=0.02678 tr-acc=99.14% tr-macroF1=98.97% patience=1/5 val-loss=0.55C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 8
Performing a final training pass over the validation set...


[I 2024-10-30 19:39:35,559] Trial 36 finished with value: 0.7699069117109854 and parameters: {'embedding_size': 185, 'hidden_size': 268, 'optimizer': 'Adam', 'lr': 0.0003668286526745206, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 3, 'T_mult': 3}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.49046850204467773 - Best f1 on validation set: 0.7699069117109854
Starting trial 37 with parameters:
    Embedding size: 200 - Hidden size: 283
    Optimizer: Adam (lr: 0.000501975680366069) - Scheduler: CosineAnnealingLR (params: {'T_max': 6})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=18 tr-loss=0.09121 tr-acc=96.81% tr-macroF1=96.21% patience=1/5 val-loss=0.63C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 13
Performing a final training pass over the validation set...


[I 2024-10-30 19:47:04,283] Trial 37 finished with value: 0.794997159737679 and parameters: {'embedding_size': 200, 'hidden_size': 283, 'optimizer': 'Adam', 'lr': 0.000501975680366069, 'scheduler': 'CosineAnnealingLR', 'T_max': 6}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.648291289806366 - Best f1 on validation set: 0.794997159737679
Starting trial 38 with parameters:
    Embedding size: 178 - Hidden size: 270
    Optimizer: Adam (lr: 1.6385199948579347e-05) - Scheduler: CosineAnnealingLR (params: {'T_max': 10})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=6 tr-loss=0.57858 tr-acc=70.57% tr-macroF1=48.11% patience=1/5 val-loss=0.578C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 1
Performing a final training pass over the validation set...


[I 2024-10-30 19:49:17,929] Trial 38 finished with value: 0.4104912572855953 and parameters: {'embedding_size': 178, 'hidden_size': 270, 'optimizer': 'Adam', 'lr': 1.6385199948579347e-05, 'scheduler': 'CosineAnnealingLR', 'T_max': 10}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.6072590351104736 - Best f1 on validation set: 0.4104912572855953
Starting trial 39 with parameters:
    Embedding size: 171 - Hidden size: 260
    Optimizer: Adam (lr: 7.412761369975003e-05) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 7, 'T_mult': 4})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=14 tr-loss=0.19748 tr-acc=93.09% tr-macroF1=91.63% patience=1/5 val-loss=0.42C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 9
Performing a final training pass over the validation set...


[I 2024-10-30 19:54:10,981] Trial 39 finished with value: 0.7429887155658812 and parameters: {'embedding_size': 171, 'hidden_size': 260, 'optimizer': 'Adam', 'lr': 7.412761369975003e-05, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 7, 'T_mult': 4}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.43637366592884064 - Best f1 on validation set: 0.7429887155658812
Starting trial 40 with parameters:
    Embedding size: 156 - Hidden size: 275
    Optimizer: Adam (lr: 4.3170197455852316e-05) - Scheduler: CosineAnnealingLR (params: {'T_max': 4})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=30 tr-loss=0.21325 tr-acc=92.21% tr-macroF1=90.50% patience=1/5 val-loss=0.42C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 25
Performing a final training pass over the validation set...


[I 2024-10-30 20:04:00,520] Trial 40 finished with value: 0.7363465160075329 and parameters: {'embedding_size': 156, 'hidden_size': 275, 'optimizer': 'Adam', 'lr': 4.3170197455852316e-05, 'scheduler': 'CosineAnnealingLR', 'T_max': 4}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.42039112746715546 - Best f1 on validation set: 0.7363465160075329
Starting trial 41 with parameters:
    Embedding size: 176 - Hidden size: 267
    Optimizer: Adam (lr: 0.0007239994260249259) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 9, 'T_mult': 3})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=13 tr-loss=0.01259 tr-acc=99.72% tr-macroF1=99.67% patience=1/5 val-loss=0.77C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 8
Performing a final training pass over the validation set...


[I 2024-10-30 20:08:39,475] Trial 41 finished with value: 0.7861556743909686 and parameters: {'embedding_size': 176, 'hidden_size': 267, 'optimizer': 'Adam', 'lr': 0.0007239994260249259, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 9, 'T_mult': 3}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.5293657332658768 - Best f1 on validation set: 0.7861556743909686
Starting trial 42 with parameters:
    Embedding size: 181 - Hidden size: 263
    Optimizer: Adam (lr: 0.0006989152384656802) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 11, 'T_mult': 3})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=7 tr-loss=0.11199 tr-acc=95.74% tr-macroF1=94.91% patience=1/5 val-loss=0.532C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 2
Performing a final training pass over the validation set...


[I 2024-10-30 20:11:15,656] Trial 42 finished with value: 0.7827763378424172 and parameters: {'embedding_size': 181, 'hidden_size': 263, 'optimizer': 'Adam', 'lr': 0.0006989152384656802, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 11, 'T_mult': 3}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.4423588663339615 - Best f1 on validation set: 0.7827763378424172
Starting trial 43 with parameters:
    Embedding size: 173 - Hidden size: 271
    Optimizer: Adam (lr: 0.0009020739014232177) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 8, 'T_mult': 2})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=15 tr-loss=0.03839 tr-acc=98.64% tr-macroF1=98.39% patience=1/5 val-loss=0.66C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 10
Performing a final training pass over the validation set...


[I 2024-10-30 20:16:35,659] Trial 43 finished with value: 0.7889716840536513 and parameters: {'embedding_size': 173, 'hidden_size': 271, 'optimizer': 'Adam', 'lr': 0.0009020739014232177, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 8, 'T_mult': 2}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.5319197624921799 - Best f1 on validation set: 0.7889716840536513
Starting trial 44 with parameters:
    Embedding size: 169 - Hidden size: 269
    Optimizer: Adam (lr: 0.0006372736299660221) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 9, 'T_mult': 4})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=11 tr-loss=0.03038 tr-acc=99.12% tr-macroF1=98.95% patience=1/5 val-loss=0.66C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 6
Performing a final training pass over the validation set...


[I 2024-10-30 20:20:25,242] Trial 44 finished with value: 0.7913838650680756 and parameters: {'embedding_size': 169, 'hidden_size': 269, 'optimizer': 'Adam', 'lr': 0.0006372736299660221, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 9, 'T_mult': 4}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.43063829839229584 - Best f1 on validation set: 0.7913838650680756
Starting trial 45 with parameters:
    Embedding size: 161 - Hidden size: 265
    Optimizer: Adam (lr: 0.00010881014372510626) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 11, 'T_mult': 2})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=18 tr-loss=0.10888 tr-acc=96.60% tr-macroF1=95.94% patience=1/5 val-loss=0.43C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 13
Performing a final training pass over the validation set...


[I 2024-10-30 20:26:25,885] Trial 45 finished with value: 0.7551585014409221 and parameters: {'embedding_size': 161, 'hidden_size': 265, 'optimizer': 'Adam', 'lr': 0.00010881014372510626, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 11, 'T_mult': 2}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.40219658613204956 - Best f1 on validation set: 0.7551585014409221
Starting trial 46 with parameters:
    Embedding size: 153 - Hidden size: 275
    Optimizer: Adam (lr: 0.0003754813072579791) - Scheduler: CosineAnnealingWarmRestarts (params: {'T_0': 5, 'T_mult': 5})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=8 tr-loss=0.05993 tr-acc=98.21% tr-macroF1=97.87% patience=1/5 val-loss=0.478C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 3
Performing a final training pass over the validation set...


[I 2024-10-30 20:29:06,233] Trial 46 finished with value: 0.7854237981012078 and parameters: {'embedding_size': 153, 'hidden_size': 275, 'optimizer': 'Adam', 'lr': 0.0003754813072579791, 'scheduler': 'CosineAnnealingWarmRestarts', 'T_0': 5, 'T_mult': 5}. Best is trial 9 with value: 0.8068037111151537.


[Training complete] - Best loss on validation set: 0.42369110882282257 - Best f1 on validation set: 0.7854237981012078
Starting trial 47 with parameters:
    Embedding size: 195 - Hidden size: 278
    Optimizer: Adam (lr: 0.0005161449102180434) - Scheduler: CosineAnnealingLR (params: {'T_max': 11})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=14 tr-loss=0.03197 tr-acc=99.20% tr-macroF1=99.05% patience=1/5 val-loss=0.69C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 9
Performing a final training pass over the validation set...


[I 2024-10-30 20:34:47,091] Trial 47 finished with value: 0.8110541940329175 and parameters: {'embedding_size': 195, 'hidden_size': 278, 'optimizer': 'Adam', 'lr': 0.0005161449102180434, 'scheduler': 'CosineAnnealingLR', 'T_max': 11}. Best is trial 47 with value: 0.8110541940329175.


[Training complete] - Best loss on validation set: 0.47745291888713837 - Best f1 on validation set: 0.8110541940329175
Starting trial 48 with parameters:
    Embedding size: 186 - Hidden size: 288
    Optimizer: Adam (lr: 0.0002590951849208455) - Scheduler: CosineAnnealingLR (params: {'T_max': 11})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=14 tr-loss=0.04482 tr-acc=98.67% tr-macroF1=98.41% patience=1/5 val-loss=0.54C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 9
Performing a final training pass over the validation set...


[I 2024-10-30 20:40:13,149] Trial 48 finished with value: 0.786531279178338 and parameters: {'embedding_size': 186, 'hidden_size': 288, 'optimizer': 'Adam', 'lr': 0.0002590951849208455, 'scheduler': 'CosineAnnealingLR', 'T_max': 11}. Best is trial 47 with value: 0.8110541940329175.


[Training complete] - Best loss on validation set: 0.40929220616817474 - Best f1 on validation set: 0.786531279178338
Starting trial 49 with parameters:
    Embedding size: 195 - Hidden size: 278
    Optimizer: Adam (lr: 0.000523688821899043) - Scheduler: CosineAnnealingLR (params: {'T_max': 9})
[NeuralNetwork running on cpu]


[CNNnet] training epoch=8 tr-loss=0.05311 tr-acc=98.11% tr-macroF1=97.74% patience=1/5 val-loss=0.487C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:672: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoint/relations/classifier_net.dat from epoch 3
Performing a final training pass over the validation set...


[I 2024-10-30 20:43:29,176] Trial 49 finished with value: 0.7943555065857224 and parameters: {'embedding_size': 195, 'hidden_size': 278, 'optimizer': 'Adam', 'lr': 0.000523688821899043, 'scheduler': 'CosineAnnealingLR', 'T_max': 9}. Best is trial 47 with value: 0.8110541940329175.


[Training complete] - Best loss on validation set: 0.3936632573604584 - Best f1 on validation set: 0.7943555065857224
Best trial:
  Macro F1 Score: 0.8110541940329175
  Params:
    embedding_size: 195
    hidden_size: 278
    optimizer: Adam
    lr: 0.0005161449102180434
    scheduler: CosineAnnealingLR
    T_max: 11


We can now train and test using the obtained hyperparameters.

In [14]:
set_seed(42)

embedding_size = 195
hidden_size = 278   
lr = 0.0005161449102180434

cnn_module = CNNnet(
    abs_dataset.vocabulary_size,
    abs_dataset.training.n_classes,
    embedding_size=embedding_size,
    hidden_size=hidden_size
)

optimizer = Adam(cnn_module.parameters(), lr=lr)
scheduler = CosineAnnealingLR(optimizer, T_max=11)

cnn_classifier = ScheduledNeuralClassifierTrainer(
    cnn_module,
    lr_scheduler=scheduler,
    optim = optimizer,
    device='cpu',
    checkpointpath='../checkpoints/relations/classifier_net.dat',
    padding_length=107,
    patience=10
)

cnn_classifier.fit(*abs_dataset.training.Xy, *abs_dataset.val.Xy)

[NeuralNetwork running on cpu]


[CNNnet] training epoch=19 tr-loss=0.02235 tr-acc=99.31% tr-macroF1=99.18% patience=1/10 val-loss=0.6C:\Users\Antonio\Documents\UniBO\NLP\project\nlp_unibo_2023-24_project\experiments_antonio\experiment_4_code.py:671: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded f

Training ended by patience exhausted; loading best model parameters from ../checkpoints/relations/classifier_net.dat from epoch 9
Performing a final training pass over the validation set...
[Training complete] - Best loss on validation set: 0.47745291888713837 - Best f1 on validation set: 0.8110541940329175


In [15]:
f1_train = 1-qp.error.f1e(abs_dataset.training.labels, cnn_classifier.predict(abs_dataset.training.instances))
accuracy_train = 1-qp.error.acce(abs_dataset.training.labels, cnn_classifier.predict(abs_dataset.training.instances))
print('- Train set:')
print(f'\tF1: {f1_train}')    
print(f'\tAccuracy: {accuracy_train}')    

f1_test_glaucoma = 1-qp.error.f1e(glaucoma_collection.labels, cnn_classifier.predict(glaucoma_collection.instances))
accuracy_test_glaucoma = 1-qp.error.acce(glaucoma_collection.labels, cnn_classifier.predict(glaucoma_collection.instances))

print('- Glaucoma test set:')
print(f'\tF1: {f1_test_glaucoma}')    
print(f'\tAccuracy: {accuracy_test_glaucoma}')    

f1_test_neoplasm = 1-qp.error.f1e(neoplasm_collection.labels, cnn_classifier.predict(neoplasm_collection.instances))
accuracy_test_neoplasm = 1-qp.error.acce(neoplasm_collection.labels, cnn_classifier.predict(neoplasm_collection.instances))

print('- Neoplasm test set:')
print(f'\tF1: {f1_test_neoplasm}')    
print(f'\tAccuracy: {accuracy_test_neoplasm}')

f1_test_mixed = 1-qp.error.f1e(mixed_collection.labels, cnn_classifier.predict(mixed_collection.instances))
accuracy_test_mixed = 1-qp.error.acce(mixed_collection.labels, cnn_classifier.predict(mixed_collection.instances))

print('- Mixed test set:')
print(f'\tF1: {f1_test_mixed}')    
print(f'\tAccuracy: {accuracy_test_mixed}')

- Train set:
	F1: 0.9992308085066453
	Accuracy: 0.9993541442411195
- Glaucoma test set:
	F1: 0.731208145908966
	Accuracy: 0.764751552795031
- Neoplasm test set:
	F1: 0.7878662886196062
	Accuracy: 0.8205705705705706
- Mixed test set:
	F1: 0.7414842889520707
	Accuracy: 0.7855960264900662


In [16]:
infer(test_set, indexer, comp_quantifier=None, comp_classifier=None, rel_quantifier=None, rel_classifier=cnn_classifier, filename=None, use_tokenizer=True)

File 9643663 - Relations: [0] - Text:
 To evaluate the efficacy and tolerability of 'Casodex' monotherapy (150 mg daily) for metastatic and locally advanced prostate cancer. A total of 1,453 patients with either confirmed metastatic disease (M1), or T3/T4 non-metastatic disease with elevated prostate-specific antigen (M0) were recruited into one of two identical, multicentre, randomised studies to compare 'Casodex' 150 mg/day with castration. The protocols allowed for combined analysis. At a median follow-up period of approximately 100 weeks for both studies, 'Casodex' 150 mg was found to be less effective than castration in patients with metastatic disease (M1) at entry (hazard ratio of 1.30 for time to death) with a difference in median survival of 6 weeks. In symptomatic M1 patients, 'Casodex' was associated with a statistically significant improvement in subjective response (70%) compared with castration (58%). Analysis of a validated quality-of-life questionnaire proved an advanta

indexing: 100%|███████████████████████████████████████████████████| 13/13 [00:00<00:00, 13004.04it/s]

	Classification:
		# Ground truth relations: (0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0)
		# Predicted relations labels: [0 0 0 0 1 0 1 0 0 0 0 0 0]


We obtain worse results if compared with the components model: this is expected, as the number of positive labels is now a subgroup of the positive labels used to train the previous model, leading to an imbalanced dataset and a more difficult task.

### 3. QuaNet 
We will include the description of `QuaNet` again, as it may prove useful. `QuaNet` observes the classification predictions to learn higher-order *quantification embeddings*, which are then refined by incorporating quantification predictions of simple classify-and-count-like methods.

![architecture](./images/quanet_architecture.png)

The QuaNet architecture (see Figure 1) consists of two main components: a **recurrent component** and a **fully connected component**.

#### 3.1 Recurrent Component: Bidirectional LSTM
- The core of the model is a **Bidirectional LSTM** (Long Short-Term Memory), a type of recurrent neural network. 
- The LSTM receives as input a **list of pairs** $⟨Pr(c|x), \vec{x}⟩$, where:
  - $Pr(c|x)$ is the probability that a classifier $h$ assigns class $c$ to document $x$.
  - $\vec{x}$ is the **document embedding**, a vector representing the document's content.
- The list is **sorted by the value of $Pr(c|x)$**, meaning the documents are arranged from least to most likely to belong to class $c$.
  
The **intuition** behind this approach is that the LSTM will "learn to count" positive and negative examples. By observing the ordered sequence of probabilities, the LSTM should learn to recognize the point where the documents switch from negative to positive examples. The document embedding $\vec{x}$ helps the LSTM assign different importance to each document when making its prediction.

The output of the LSTM is called a **quantification embedding**—a dense vector representing the information about the quantification task learned from the input data.

#### 3.2 Fully Connected Component
- The vector returned by the LSTM is combined with additional information, specifically **quantification-related statistics**:
  - $\hat{p}_c^{CC}(D)$, $\hat{p}_c^{ACC}(D)$, $\hat{p}_c^{PCC}(D)$, and $\hat{p}_c^{PACC}(D)$, which are quantification predictions from different methods.
  - $tpr_b$, $fpr_b$, $tpr_s$, and $fpr_s$, aggregate statistics related to true positive and false positive rates, which are easy to compute from the classifier $h$ using a validation set.

This combined vector then passes through the second part of the architecture, which is made up of **fully connected layers** with **ReLU activations**. These layers adjust the quantification embedding using the additional statistics from the classifier to improve the accuracy of the quantification.

The final output is a prediction $\hat{p}_c^{QuaNet}(c|D)$, which represents the probability of class $c$ for the dataset $D$, produced by a **softmax layer**.

QuaNet could use quantification predictions from many methods, but it focuses on those that are **computationally efficient** (like CC, ACC, PCC, and PACC). This ensures that the process remains fast while still providing sufficient information for accurate predictions.

### Details

| Layer | Type | Dimensions | Activation | Dropout |
|---|---|---|---|---|
| Input | LSTM | 128 | N/A | N/A |
| Dense 1 | Dense | 1024 | ReLU | 0.5 |
| Dense 2 | Dense | 512 | ReLU | 0.5 |
| Output | Dense | 2 | Softmax | N/A |

- The LSTM has **64 hidden dimensions**, and since it’s bidirectional, the final LSTM output has **128 dimensions**.
- This LSTM output is concatenated with the **8 quantification statistics** (giving a total of 136 dimensions), which is then fed into:
  - **Two dense layers** with **1,024** and **512 dimensions**, each using **ReLU activation** and **0.5 dropout**.
  - Finally, the output is passed through a **softmax layer** of size 2 to make the final class prediction.


In [17]:
# train QuaNet (alternatively, we can set fit_classifier=True and let QuaNet train the classifier)
set_seed(42)

quantifier = QuaNet(cnn_classifier, qp.environ['SAMPLE_SIZE'], qdrop_p=0, device='cpu', checkpointdir='../checkpoints/relations', checkpointname='Quanet-Relations')
quantifier.fit(abs_dataset.training, fit_classifier=False)

QuaNetModule(
  (lstm): LSTM(102, 64, batch_first=True, bidirectional=True)
  (dropout): Dropout(p=0, inplace=False)
  (ff_layers): ModuleList(
    (0): Linear(in_features=136, out_features=1024, bias=True)
    (1): Linear(in_features=1024, out_features=512, bias=True)
  )
  (output): Linear(in_features=512, out_features=2, bias=True)
)


  0%|                                                                        | 0/500 [00:00<?, ?it/s]C:\Users\Antonio\anaconda3\envs\NLP\Lib\site-packages\quapy\method\_neural.py:233: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_new.cpp:281.)
  ptrue = torch.as_tensor([sample_data.prevalence()], dtype=torch.float, device=self.device)
[QuaNet] epoch=1 [it=499/500]	tr-mseloss=0.00379 tr-maeloss=0.03395	val-mseloss=-1.00000 val-maeloss=
100%|██████████████████████████████████████████████████████████████| 100/100 [00:02<00:00, 48.47it/s]
[QuaNet] epoch=2 [it=499/500]	tr-mseloss=0.00036 tr-maeloss=0.01412	val-mseloss=0.00048 val-maeloss=0
100%|██████████████████████████████████████████████████████████████| 100/100 [00:02<00:00, 49.54it

training ended by patience exhausted; loading best model parameters in ../checkpoints/relations\Quanet-Relations for epoch 29



C:\Users\Antonio\anaconda3\envs\NLP\Lib\site-packages\quapy\method\_neural.py:188: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.quanet.load_state_dict(torch.load(chec

QuaNetTrainer(classifier__batch_size=64, classifier__batch_size_test=512,
              classifier__device=device(type='cpu'), classifier__drop_p=0.5,
              classifier__embedding_size=195, classifier__epochs=200,
              classifier__hidden_size=278, classifier__kernel_heights=[3, 5, 7],
              classifier__lr=0.001, classifier__padding_length=107,
              classifier__patience=10, classifier__repr_size=100,
              classifier__stride=1, classifier__weight_decay=0, qdrop_p=0)

In [26]:
print('- Train set:')
result_train = evaluate(collection=abs_dataset.training, n=[1,3,5,10, qp.environ['SAMPLE_SIZE'], 15], quantifier=quantifier)

print('- Val set:')
result_train = evaluate(collection=abs_dataset.val, n=[1,3,5,10, qp.environ['SAMPLE_SIZE'], 15], quantifier=quantifier)

print('- Glaucoma test set:')
result_test = evaluate(collection=glaucoma_collection, n=[1,3,5,10, qp.environ['SAMPLE_SIZE'], 15], quantifier=quantifier)

print('- Neoplasm test set:')
result_test = evaluate(collection=neoplasm_collection, n=[1,3,5,10, qp.environ['SAMPLE_SIZE'], 15], quantifier=quantifier)

print('- Mixed test set:')
result_test = evaluate(collection=mixed_collection, n=[1,3,5,10, qp.environ['SAMPLE_SIZE'], 15], quantifier=quantifier)

- Train set:
Error Metric	Standard	ByDoc (n=1)	ByDoc (n=3)	ByDoc (n=5)	ByDoc (n=10)	ByDoc (n=13)	ByDoc (n=15)
------------	--------	-----------	-----------	-----------	------------	------------	------------
AE             	0.0004         	0.0026         	0.0021         	0.0019         	0.0016         	0.0014         	0.0018         
RAE            	0.0009         	0.0069         	0.0047         	0.0041         	0.0034         	0.0031         	0.0039         
MSE            	0.0000         	0.0000         	0.0000         	0.0000         	0.0000         	0.0000         	0.0000         
MAE            	0.0004         	0.0026         	0.0021         	0.0019         	0.0016         	0.0014         	0.0018         
MRAE           	0.0009         	0.0069         	0.0047         	0.0041         	0.0034         	0.0031         	0.0039         
MKLD           	0.0000         	0.0001         	0.0000         	0.0000         	0.0000         	0.0000         	0.0000         
- Val set:
Error Metric	S

As expected, results are once again slightly worse, reflecting the increased difficulty of the task.

In [ ]:
infer(test_set, indexer, comp_quantifier=None, comp_classifier=None, rel_quantifier=quantifier, rel_classifier=cnn_classifier, filename=None, use_tokenizer=True)